name: build deploy and test application
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the repository
      uses: actions/checkout@v4
    - name: build node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - run: npm install
    - run: npm run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout the repository
      uses: actions/checkout@v4
    - name: test node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - run: npm install
    - run: npm run test
    
