name: build deploy and test application
on: push
jobs:
  checkout-repository-download-files:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the repository
      uses: actions/checkout@v4
    - name: build node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - run: npm install
    - run: npm run build
      
    
